setup(
    name='facer',
    version="1.0",
    packages=[
        'facer'
        ],
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'flask',
        'flask_cors',
    ]
)
